[tool.isort]
profile = "black"
color_output = true
known_first_party = ["assistance"]

[tool.pyright]
ignore = [
    "**/node_modules",
    "**/__pycache__",
    "**/BUILD",
]

typeCheckingMode = "strict"
