[tool.isort]
profile = "black"
color_output = true
known_first_party = ["assistance"]

[tool.pyright]
ignore = [
    "**/node_modules",
    "**/__pycache__",
    "./src/python/assistance/_client"
]

# typeCheckingMode = "strict"


[tool.pylint.master]
ignore-patterns = "BUILD"

[tool.pylint.messages-control]
disable = [
    "fixme",
    "line-too-long",
    "missing-function-docstring",
    "no-name-in-module",
    "missing-class-docstring",
    "too-few-public-methods",
    "invalid-name",
    "missing-module-docstring",
    "no-member",
    "logging-fstring-interpolation",
]

[tool.pylint.design]
max-locals = 25
max-args = 8
