name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Perform CI Checks

    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Pants
        run: |
          /bin/bash -c "$(curl -fsSL https://static.pantsbuild.org/setup/pantsup.sh)"

      - name: Check BUILD files
        run: |
          pants tailor --check update-build-files --check ::

      - name: Lint and typecheck
        run: |
          pants lint check ::

      - name: Test
        run: |
          pants test ::

      - name: Package
        run: |
          pants package ::
